name: ludo_game
description: A Ludo Dice Game for four players

environment:
  sdk: ">=2.12.0 <3.0.0" # Adjust based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  

flutter:
  uses-material-design: true
